sudo: false
language: node_js
node_js:
  - "6.1"
sudo: false
env:
  - PROJECT=[ "$TRAVIS_TAG" ] && ${FIREBASE_PROJECT_ID} || ${FIREBASE_PROJECT_ID_DEV}
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: "${PROJECT}"
    on:
      branch: master
# notifications:
#  slack: "${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_ROOM}"
