sudo: false
language: node_js
node_js:
  - "6.1"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run build
  - if [[ $TRAVIS_TAG == "" ]]; then FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID_DEV; fi;
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: ${FIREBASE_PROJECT_ID}
    on:
      branch: master
# notifications:
#  slack: "${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_ROOM}"
