sudo: false
language: node_js
node_js:
  - "6.1"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower
  - npm install -g polymer-cli
  - npm install
  - bower install
script:
  - npm run build
deploy:
  edge: true
  provider: firebase
  skip_cleanup: true
  project: "${FIREBASE_PROJECT_ID}"
  on:
    tag: true
deploy:
  edge: true
  provider: firebase
  skip_cleanup: true
  project: "${FIREBASE_PROJECT_ID_DEV}"
  on:
    branch: master
# notifications:
#  slack: "${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_ROOM}"
