sudo: false
language: node_js
node_js:
  - "6.1"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower
  - npm install -g polymer-cli
  - npm install
  - bower install
before_script:
  - npm run lint
script:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    project: 'if [ "$TRAVIS_TAG" ]; then ${FIREBASE_PROJECT_ID} else ${FIREBASE_PROJECT_ID_DEV} fi'
    on:
      branch: master
# notifications:
#  slack: "${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_ROOM}"
