sudo: false
language: node_js
node_js:
  - "6.1"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: ${FIREBASE_PROJECT_ID_DEV}
    on:
      branch: master
      tags: false
  - provider: firebase
    edge: true
    skip_cleanup: true
    overwrite: true
    project: ${FIREBASE_PROJECT_ID}
    on:
      branch: master
      tags: true
# notifications:
#  slack: "${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_ROOM}"
